/*
 * Copyright (C) ExBin Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.framework.bined.kaitai.gui;

import java.awt.Component;
import java.awt.event.MouseEvent;
import java.util.ResourceBundle;
import javax.annotation.Nonnull;
import javax.annotation.ParametersAreNonnullByDefault;
import javax.swing.JPopupMenu;
import javax.swing.tree.DefaultTreeModel;
import org.exbin.framework.language.api.LanguageModuleApi;
import org.exbin.framework.App;
import org.exbin.framework.menu.popup.api.MenuPopupModuleApi;
import org.exbin.framework.utils.DesktopUtils;

/**
 * Kaitai definitions preview panel.
 *
 * @author ExBin Project (https://exbin.org)
 */
@ParametersAreNonnullByDefault
public class KaitaiDefinitionPreviewPanel extends javax.swing.JPanel {

    public static final String GALLERY_LINK = "https://formats.kaitai.io/%s/";
    public static final String GALLERY_LINK_HTML = "<html><body><a href=\"%s\">%s</a></body></html>";
    protected final java.util.ResourceBundle resourceBundle = App.getModule(LanguageModuleApi.class).getBundle(KaitaiDefinitionPreviewPanel.class);
    protected DefaultTreeModel definitionsTreeModel;
    protected String galleryLink = "";

    public KaitaiDefinitionPreviewPanel() {
        initComponents();
        init();
    }

    private void init() {
        galleryLinkLabel.setComponentPopupMenu(new JPopupMenu() {

            @Override
            public void show(Component invoker, int x, int y) {
                MenuPopupModuleApi menuPopupModule = App.getModule(MenuPopupModuleApi.class);
                menuPopupModule.createLinkPopupMenu(galleryLink).show(invoker, x, y);
            }
        });
    }

    @Nonnull
    public ResourceBundle getResourceBundle() {
        return resourceBundle;
    }

    public void setData(String title, String id, String extension, String mimeType) {
        titleTextField.setText(title);
        idTextField.setText(id);
        galleryLink = String.format(GALLERY_LINK, id);
        galleryLinkLabel.setText(String.format(GALLERY_LINK_HTML, galleryLink, id));
        extensionTextField.setText(extension);
        mimeTypeTextField.setText(mimeType);
    }

    public void clearData() {
        setData("", "", "", "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        galleryLabel = new javax.swing.JLabel();
        galleryLinkLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        extensionLabel = new javax.swing.JLabel();
        extensionTextField = new javax.swing.JTextField();
        mimeTypeLabel = new javax.swing.JLabel();
        mimeTypeTextField = new javax.swing.JTextField();

        titleLabel.setText(resourceBundle.getString("titleLabel.text")); // NOI18N

        titleTextField.setEditable(false);

        galleryLabel.setText(resourceBundle.getString("galleryLabel.text")); // NOI18N

        galleryLinkLabel.setText("link");
        galleryLinkLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        galleryLinkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                galleryLinkLabelMouseClicked(evt);
            }
        });

        idLabel.setText(resourceBundle.getString("idLabel.text")); // NOI18N

        idTextField.setEditable(false);

        extensionLabel.setText(resourceBundle.getString("extensionLabel.text")); // NOI18N

        extensionTextField.setEditable(false);

        mimeTypeLabel.setText(resourceBundle.getString("mimeTypeLabel.text")); // NOI18N

        mimeTypeTextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(galleryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(galleryLinkLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(idTextField)
                    .addComponent(extensionTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel)
                            .addComponent(idLabel)
                            .addComponent(extensionLabel)
                            .addComponent(mimeTypeLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(mimeTypeTextField))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(galleryLabel)
                    .addComponent(galleryLinkLabel))
                .addGap(18, 18, 18)
                .addComponent(idLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(extensionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(extensionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mimeTypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mimeTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void galleryLinkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_galleryLinkLabelMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1 && !evt.isPopupTrigger()) {
            DesktopUtils.openDesktopURL(galleryLink);
        }
    }//GEN-LAST:event_galleryLinkLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel extensionLabel;
    private javax.swing.JTextField extensionTextField;
    private javax.swing.JLabel galleryLabel;
    private javax.swing.JLabel galleryLinkLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel mimeTypeLabel;
    private javax.swing.JTextField mimeTypeTextField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTextField;
    // End of variables declaration//GEN-END:variables
}
